# .github/workflows/ci.yml
name: CI

on:
  pull_request:   # runs on PRs
  push:           # also runs on pushes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Make
        run: sudo apt-get update && sudo apt-get install -y make
      - name: Build
        run: make all