# .github/workflows/ci.yml
# Based on https://github.com/deftio/C-and-Cpp-Tests-with-CI-CD-Example/blob/master/.github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
        environment:
            description: 'The environment to run the tests in'
            required: true
            default: 'Release'
            type: choice
            options:
              - Release
              - Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make cmake
          sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libglfw3-dev
          sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

      - name: Build
        run: |
          if [ "${{ github.event.inputs.environment }}" == "Debug" ]; then
            make debug
          else
            make all
          fi